In [3]:
import numpy as np
import time

Vector Creation

In [7]:
def print_f(arr):
    print(f"array = {arr}, shape = {arr.shape}, data type = {a.dtype}")

In [8]:
a = np.zeros(4); print_f(a)
a = np.zeros((4,)); print_f(a)
a = np.random.random_sample(4); print_f(a)

array = [0. 0. 0. 0.], shape = (4,), data type = float64
array = [0. 0. 0. 0.], shape = (4,), data type = float64
array = [0.61798134 0.20372676 0.51101958 0.99449053], shape = (4,), data type = float64


In [9]:
a = np.random.rand(4); print_f(a)

array = [0.17149498 0.02908787 0.49434967 0.6352317 ], shape = (4,), data type = float64


In [11]:
a = np.arange(4.); print_f(a)

array = [0. 1. 2. 3.], shape = (4,), data type = float64


In [13]:
a = np.array([5, 4, 1, 2, 3]); print_f(a)
a = np.array([5.,4.,1.,2.,3.]); print_f(a)

array = [5 4 1 2 3], shape = (5,), data type = int64
array = [5. 4. 1. 2. 3.], shape = (5,), data type = float64


Single Vector operations

In [19]:
a

array([5., 4., 1., 2., 3.])

In [14]:
b = -a
print_f(b)

array = [-5. -4. -1. -2. -3.], shape = (5,), data type = float64


In [15]:
a ** 2

array([25., 16.,  1.,  4.,  9.])

In [22]:
np.square(a)

array([25., 16.,  1.,  4.,  9.])

In [23]:
np.sqrt(a)

array([2.23606798, 2.        , 1.        , 1.41421356, 1.73205081])

In [16]:
np.mean(a)

3.0

In [17]:
np.sum(a)

15.0

In [18]:
np.max(a)

5.0

In [20]:
np.min(a)

1.0

Vector to Vector Operations

In [27]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
b = a[10:]
a = a[:10]
print('a:'); print_f(a)
print('b:'); print_f(b)

a:
array = [0 1 2 3 4 5 6 7 8 9], shape = (10,), data type = int64
b:
array = [10 11 12 13 14 15 16 17 18 19], shape = (10,), data type = int64


In [29]:
a + b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [30]:
b - a

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [31]:
a * b

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [32]:
a / b

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

Vector - Dot Product

In [35]:
def dot_product(a, b):
    assert a.shape == b.shape, "shape of a and b should be same"
    x = 0
    for i in range(a.shape[0]):
        x += a[i] * b[i]
    return x

In [39]:
# Shape of both vectors should be same for calculating dot product
a = np.random.rand(4)
b = np.random.rand(3)
dot_product(a, b) #This should throw an error

AssertionError: shape of a and b should be same

In [40]:
a.dot(b)

ValueError: shapes (4,) and (3,) not aligned: 4 (dim 0) != 3 (dim 0)

In [41]:
a = np.random.rand(4)
b = np.random.rand(4)
dot_product(a, b) 

0.5890611732190218

In [42]:
a.dot(b)

0.5890611732190218

Vectorization vs for - loop

In [45]:
def dot_product(a, b):
    assert a.shape == b.shape, "shape of a and b should be same"
    x = 0
    for i in range(a.shape[0]):
        x += a[i] * b[i]
    return x

In [44]:
np.random.seed(42)
a = np.random.rand(10000000)
b = np.random.rand(10000000)

# Dot product using for - loop : time calculation
start = time.time()
dot_product(a,b)
end = time.time()
print(f"time taken in Dot product using for - loop = {end-start:.4f} ms")

# Dot product using Vectorization : time calculation
start = time.time()
a.dot(b)
end = time.time()
print(f"time taken in Dot product using Vectorization = {end-start:.4f} ms")


time taken in Dot product using for - loop = 1.4807 ms
time taken in Dot product using Vectorization = 0.0030 ms


Matrix Calculation

In [52]:
a = np.zeros((1,2)); print_f(a)
b = np.zeros((2,1)); print_f(b)
c = np.random.random_sample((2,2)); print_f(c)

array = [[0. 0.]], shape = (1, 2), data type = float64
array = [[0.]
 [0.]], shape = (2, 1), data type = float64
array = [[0.4001779  0.32989882]
 [0.37492043 0.28916464]], shape = (2, 2), data type = float64


In [55]:
a = np.arange(10); print_f(a)
b = a.reshape((-1, 2)); print_f(b)
c = a.reshape((2, -1)); print_f(c)

array = [0 1 2 3 4 5 6 7 8 9], shape = (10,), data type = int64
array = [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]], shape = (5, 2), data type = int64
array = [[0 1 2 3 4]
 [5 6 7 8 9]], shape = (2, 5), data type = int64


-1 in reshape method calculates the number of elements along that axis according to original shape and number of elements along the other axes. For example, a has total 10 elements. So on doing reshape((-1, 2)), it will reshape the matrix in 2 columns and 10/2=5 rows. Similarly, reshape((2, -1)) will reshape the matrix in 2 rows and 10/2=5 columns.

In [57]:
# This will throw an error
d = a.reshape((-1, -1)); print_f(d)

ValueError: can only specify one unknown dimension